// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: dbsentinel.proto

package dbsentinelv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus_Role int32

const (
	NodeStatus_NODE_ROLE_UNKNOWN NodeStatus_Role = 0
	NodeStatus_NODE_ROLE_MASTER  NodeStatus_Role = 1
	NodeStatus_NODE_ROLE_REPLICA NodeStatus_Role = 2
)

// Enum value maps for NodeStatus_Role.
var (
	NodeStatus_Role_name = map[int32]string{
		0: "NODE_ROLE_UNKNOWN",
		1: "NODE_ROLE_MASTER",
		2: "NODE_ROLE_REPLICA",
	}
	NodeStatus_Role_value = map[string]int32{
		"NODE_ROLE_UNKNOWN": 0,
		"NODE_ROLE_MASTER":  1,
		"NODE_ROLE_REPLICA": 2,
	}
)

func (x NodeStatus_Role) Enum() *NodeStatus_Role {
	p := new(NodeStatus_Role)
	*p = x
	return p
}

func (x NodeStatus_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_dbsentinel_proto_enumTypes[0].Descriptor()
}

func (NodeStatus_Role) Type() protoreflect.EnumType {
	return &file_dbsentinel_proto_enumTypes[0]
}

func (x NodeStatus_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus_Role.Descriptor instead.
func (NodeStatus_Role) EnumDescriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{0, 0}
}

type BackupRequest_BackupType int32

const (
	BackupRequest_BACKUP_TYPE_UNKNOWN BackupRequest_BackupType = 0
	BackupRequest_BACKUP_TYPE_FULL    BackupRequest_BackupType = 1
	BackupRequest_BACKUP_TYPE_WAL     BackupRequest_BackupType = 2
)

// Enum value maps for BackupRequest_BackupType.
var (
	BackupRequest_BackupType_name = map[int32]string{
		0: "BACKUP_TYPE_UNKNOWN",
		1: "BACKUP_TYPE_FULL",
		2: "BACKUP_TYPE_WAL",
	}
	BackupRequest_BackupType_value = map[string]int32{
		"BACKUP_TYPE_UNKNOWN": 0,
		"BACKUP_TYPE_FULL":    1,
		"BACKUP_TYPE_WAL":     2,
	}
)

func (x BackupRequest_BackupType) Enum() *BackupRequest_BackupType {
	p := new(BackupRequest_BackupType)
	*p = x
	return p
}

func (x BackupRequest_BackupType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupRequest_BackupType) Descriptor() protoreflect.EnumDescriptor {
	return file_dbsentinel_proto_enumTypes[1].Descriptor()
}

func (BackupRequest_BackupType) Type() protoreflect.EnumType {
	return &file_dbsentinel_proto_enumTypes[1]
}

func (x BackupRequest_BackupType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupRequest_BackupType.Descriptor instead.
func (BackupRequest_BackupType) EnumDescriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{1, 0}
}

type ListBackups_BackupType int32

const (
	ListBackups_BACKUP_TYPE_UNKNOWN ListBackups_BackupType = 0
	ListBackups_BACKUP_TYPE_FULL    ListBackups_BackupType = 1
	ListBackups_BACKUP_TYPE_WAL     ListBackups_BackupType = 2
)

// Enum value maps for ListBackups_BackupType.
var (
	ListBackups_BackupType_name = map[int32]string{
		0: "BACKUP_TYPE_UNKNOWN",
		1: "BACKUP_TYPE_FULL",
		2: "BACKUP_TYPE_WAL",
	}
	ListBackups_BackupType_value = map[string]int32{
		"BACKUP_TYPE_UNKNOWN": 0,
		"BACKUP_TYPE_FULL":    1,
		"BACKUP_TYPE_WAL":     2,
	}
)

func (x ListBackups_BackupType) Enum() *ListBackups_BackupType {
	p := new(ListBackups_BackupType)
	*p = x
	return p
}

func (x ListBackups_BackupType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListBackups_BackupType) Descriptor() protoreflect.EnumDescriptor {
	return file_dbsentinel_proto_enumTypes[2].Descriptor()
}

func (ListBackups_BackupType) Type() protoreflect.EnumType {
	return &file_dbsentinel_proto_enumTypes[2]
}

func (x ListBackups_BackupType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListBackups_BackupType.Descriptor instead.
func (ListBackups_BackupType) EnumDescriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{10, 0}
}

type NodeStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role           NodeStatus_Role        `protobuf:"varint,2,opt,name=role,proto3,enum=dbsentinel.NodeStatus_Role" json:"role,omitempty"`
	LagSeconds     *durationpb.Duration   `protobuf:"bytes,3,opt,name=lag_seconds,json=lagSeconds,proto3" json:"lag_seconds,omitempty"`
	UptimeSeconds  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Metrics        map[string]string      `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., "size_bytes", "active_connections"
	ClusterVersion uint32                 `protobuf:"varint,6,opt,name=cluster_version,json=clusterVersion,proto3" json:"cluster_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_dbsentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetRole() NodeStatus_Role {
	if x != nil {
		return x.Role
	}
	return NodeStatus_NODE_ROLE_UNKNOWN
}

func (x *NodeStatus) GetLagSeconds() *durationpb.Duration {
	if x != nil {
		return x.LagSeconds
	}
	return nil
}

func (x *NodeStatus) GetUptimeSeconds() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSeconds
	}
	return nil
}

func (x *NodeStatus) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *NodeStatus) GetClusterVersion() uint32 {
	if x != nil {
		return x.ClusterVersion
	}
	return 0
}

type BackupRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DatabaseName  string                   `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	BackupType    BackupRequest_BackupType `protobuf:"varint,2,opt,name=backup_type,json=backupType,proto3,enum=dbsentinel.BackupRequest_BackupType" json:"backup_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_dbsentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{1}
}

func (x *BackupRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *BackupRequest) GetBackupType() BackupRequest_BackupType {
	if x != nil {
		return x.BackupType
	}
	return BackupRequest_BACKUP_TYPE_UNKNOWN
}

type BackupProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackupId        string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	ProgressPercent uint32                 `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"` // e.g. "Dumping table users...", "Compressing..."
	IsCompleted     bool                   `protobuf:"varint,4,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BackupProgress) Reset() {
	*x = BackupProgress{}
	mi := &file_dbsentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupProgress) ProtoMessage() {}

func (x *BackupProgress) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupProgress.ProtoReflect.Descriptor instead.
func (*BackupProgress) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{2}
}

func (x *BackupProgress) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupProgress) GetProgressPercent() uint32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *BackupProgress) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *BackupProgress) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type VerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_dbsentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

type VerificationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackupId        string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RestoreTimeMs   *durationpb.Duration   `protobuf:"bytes,3,opt,name=restore_time_ms,json=restoreTimeMs,proto3" json:"restore_time_ms,omitempty"`
	VerificationLog string                 `protobuf:"bytes,4,opt,name=verification_log,json=verificationLog,proto3" json:"verification_log,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerificationResult) Reset() {
	*x = VerificationResult{}
	mi := &file_dbsentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResult) ProtoMessage() {}

func (x *VerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResult.ProtoReflect.Descriptor instead.
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{4}
}

func (x *VerificationResult) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *VerificationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerificationResult) GetRestoreTimeMs() *durationpb.Duration {
	if x != nil {
		return x.RestoreTimeMs
	}
	return nil
}

func (x *VerificationResult) GetVerificationLog() string {
	if x != nil {
		return x.VerificationLog
	}
	return ""
}

type FailoverRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetReplicaId string                 `protobuf:"bytes,1,opt,name=target_replica_id,json=targetReplicaId,proto3" json:"target_replica_id,omitempty"`
	Force           bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	ClusterVersion  uint32                 `protobuf:"varint,3,opt,name=cluster_version,json=clusterVersion,proto3" json:"cluster_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FailoverRequest) Reset() {
	*x = FailoverRequest{}
	mi := &file_dbsentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailoverRequest) ProtoMessage() {}

func (x *FailoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailoverRequest.ProtoReflect.Descriptor instead.
func (*FailoverRequest) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{5}
}

func (x *FailoverRequest) GetTargetReplicaId() string {
	if x != nil {
		return x.TargetReplicaId
	}
	return ""
}

func (x *FailoverRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *FailoverRequest) GetClusterVersion() uint32 {
	if x != nil {
		return x.ClusterVersion
	}
	return 0
}

type FailoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailoverResponse) Reset() {
	*x = FailoverResponse{}
	mi := &file_dbsentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailoverResponse) ProtoMessage() {}

func (x *FailoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailoverResponse.ProtoReflect.Descriptor instead.
func (*FailoverResponse) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{6}
}

func (x *FailoverResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *FailoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FailoverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNodeStatusRequest) Reset() {
	*x = StreamNodeStatusRequest{}
	mi := &file_dbsentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNodeStatusRequest) ProtoMessage() {}

func (x *StreamNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{7}
}

func (x *StreamNodeStatusRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupIds     []string               `protobuf:"bytes,1,rep,name=backup_ids,json=backupIds,proto3" json:"backup_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_dbsentinel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{8}
}

func (x *ListBackupsRequest) GetBackupIds() []string {
	if x != nil {
		return x.BackupIds
	}
	return nil
}

type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListBackups   []*ListBackups         `protobuf:"bytes,1,rep,name=list_backups,json=listBackups,proto3" json:"list_backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_dbsentinel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{9}
}

func (x *ListBackupsResponse) GetListBackups() []*ListBackups {
	if x != nil {
		return x.ListBackups
	}
	return nil
}

type ListBackups struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	BackupType    ListBackups_BackupType `protobuf:"varint,2,opt,name=backup_type,json=backupType,proto3,enum=dbsentinel.ListBackups_BackupType" json:"backup_type,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackups) Reset() {
	*x = ListBackups{}
	mi := &file_dbsentinel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackups) ProtoMessage() {}

func (x *ListBackups) ProtoReflect() protoreflect.Message {
	mi := &file_dbsentinel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackups.ProtoReflect.Descriptor instead.
func (*ListBackups) Descriptor() ([]byte, []int) {
	return file_dbsentinel_proto_rawDescGZIP(), []int{10}
}

func (x *ListBackups) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *ListBackups) GetBackupType() ListBackups_BackupType {
	if x != nil {
		return x.BackupType
	}
	return ListBackups_BACKUP_TYPE_UNKNOWN
}

func (x *ListBackups) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListBackups) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_dbsentinel_proto protoreflect.FileDescriptor

const file_dbsentinel_proto_rawDesc = "" +
	"\n" +
	"\x10dbsentinel.proto\x12\n" +
	"dbsentinel\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xc5\x03\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12/\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1b.dbsentinel.NodeStatus.RoleR\x04role\x12:\n" +
	"\vlag_seconds\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"lagSeconds\x12A\n" +
	"\x0euptime_seconds\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ruptimeSeconds\x12=\n" +
	"\ametrics\x18\x05 \x03(\v2#.dbsentinel.NodeStatus.MetricsEntryR\ametrics\x12'\n" +
	"\x0fcluster_version\x18\x06 \x01(\rR\x0eclusterVersion\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x04Role\x12\x15\n" +
	"\x11NODE_ROLE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10NODE_ROLE_MASTER\x10\x01\x12\x15\n" +
	"\x11NODE_ROLE_REPLICA\x10\x02\"\xcf\x01\n" +
	"\rBackupRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12F\n" +
	"\vbackup_type\x18\x02 \x01(\x0e2%.dbsentinel.BackupRequest.Backup_typeR\n" +
	"backupType\"Q\n" +
	"\vBackup_type\x12\x17\n" +
	"\x13BACKUP_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10BACKUP_TYPE_FULL\x10\x01\x12\x13\n" +
	"\x0fBACKUP_TYPE_WAL\x10\x02\"\xa2\x01\n" +
	"\x0eBackupProgress\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\rR\x0fprogressPercent\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\x12!\n" +
	"\fis_completed\x18\x04 \x01(\bR\visCompleted\"2\n" +
	"\x13VerificationRequest\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\"\xb9\x01\n" +
	"\x12VerificationResult\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12A\n" +
	"\x0frestore_time_ms\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rrestoreTimeMs\x12)\n" +
	"\x10verification_log\x18\x04 \x01(\tR\x0fverificationLog\"|\n" +
	"\x0fFailoverRequest\x12*\n" +
	"\x11target_replica_id\x18\x01 \x01(\tR\x0ftargetReplicaId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0fcluster_version\x18\x03 \x01(\rR\x0eclusterVersion\"e\n" +
	"\x10FailoverResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"8\n" +
	"\x17StreamNodeStatusRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"3\n" +
	"\x12ListBackupsRequest\x12\x1d\n" +
	"\n" +
	"backup_ids\x18\x01 \x03(\tR\tbackupIds\"Q\n" +
	"\x13ListBackupsResponse\x12:\n" +
	"\flist_backups\x18\x01 \x03(\v2\x17.dbsentinel.ListBackupsR\vlistBackups\"\x98\x02\n" +
	"\vListBackups\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12D\n" +
	"\vbackup_type\x18\x02 \x01(\x0e2#.dbsentinel.ListBackups.Backup_typeR\n" +
	"backupType\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Q\n" +
	"\vBackup_type\x12\x17\n" +
	"\x13BACKUP_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10BACKUP_TYPE_FULL\x10\x01\x12\x13\n" +
	"\x0fBACKUP_TYPE_WAL\x10\x022\xb7\x03\n" +
	"\x11DBSentinelService\x12S\n" +
	"\x10StreamNodeStatus\x12#.dbsentinel.StreamNodeStatusRequest\x1a\x16.dbsentinel.NodeStatus\"\x000\x01\x12J\n" +
	"\rTriggerBackup\x12\x19.dbsentinel.BackupRequest\x1a\x1a.dbsentinel.BackupProgress\"\x000\x01\x12_\n" +
	"\x1aTriggerRestoreVerification\x12\x1f.dbsentinel.VerificationRequest\x1a\x1e.dbsentinel.VerificationResult\"\x00\x12N\n" +
	"\x0fTriggerFailover\x12\x1b.dbsentinel.FailoverRequest\x1a\x1c.dbsentinel.FailoverResponse\"\x00\x12P\n" +
	"\vListBackups\x12\x1e.dbsentinel.ListBackupsRequest\x1a\x1f.dbsentinel.ListBackupsResponse\"\x00B Z\x1epkg/pb/dbsentinel;dbsentinelv1b\x06proto3"

var (
	file_dbsentinel_proto_rawDescOnce sync.Once
	file_dbsentinel_proto_rawDescData []byte
)

func file_dbsentinel_proto_rawDescGZIP() []byte {
	file_dbsentinel_proto_rawDescOnce.Do(func() {
		file_dbsentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dbsentinel_proto_rawDesc), len(file_dbsentinel_proto_rawDesc)))
	})
	return file_dbsentinel_proto_rawDescData
}

var file_dbsentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dbsentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_dbsentinel_proto_goTypes = []any{
	(NodeStatus_Role)(0),            // 0: dbsentinel.NodeStatus.Role
	(BackupRequest_BackupType)(0),   // 1: dbsentinel.BackupRequest.Backup_type
	(ListBackups_BackupType)(0),     // 2: dbsentinel.ListBackups.Backup_type
	(*NodeStatus)(nil),              // 3: dbsentinel.NodeStatus
	(*BackupRequest)(nil),           // 4: dbsentinel.BackupRequest
	(*BackupProgress)(nil),          // 5: dbsentinel.BackupProgress
	(*VerificationRequest)(nil),     // 6: dbsentinel.VerificationRequest
	(*VerificationResult)(nil),      // 7: dbsentinel.VerificationResult
	(*FailoverRequest)(nil),         // 8: dbsentinel.FailoverRequest
	(*FailoverResponse)(nil),        // 9: dbsentinel.FailoverResponse
	(*StreamNodeStatusRequest)(nil), // 10: dbsentinel.StreamNodeStatusRequest
	(*ListBackupsRequest)(nil),      // 11: dbsentinel.ListBackupsRequest
	(*ListBackupsResponse)(nil),     // 12: dbsentinel.ListBackupsResponse
	(*ListBackups)(nil),             // 13: dbsentinel.ListBackups
	nil,                             // 14: dbsentinel.NodeStatus.MetricsEntry
	(*durationpb.Duration)(nil),     // 15: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
}
var file_dbsentinel_proto_depIdxs = []int32{
	0,  // 0: dbsentinel.NodeStatus.role:type_name -> dbsentinel.NodeStatus.Role
	15, // 1: dbsentinel.NodeStatus.lag_seconds:type_name -> google.protobuf.Duration
	16, // 2: dbsentinel.NodeStatus.uptime_seconds:type_name -> google.protobuf.Timestamp
	14, // 3: dbsentinel.NodeStatus.metrics:type_name -> dbsentinel.NodeStatus.MetricsEntry
	1,  // 4: dbsentinel.BackupRequest.backup_type:type_name -> dbsentinel.BackupRequest.Backup_type
	15, // 5: dbsentinel.VerificationResult.restore_time_ms:type_name -> google.protobuf.Duration
	13, // 6: dbsentinel.ListBackupsResponse.list_backups:type_name -> dbsentinel.ListBackups
	2,  // 7: dbsentinel.ListBackups.backup_type:type_name -> dbsentinel.ListBackups.Backup_type
	16, // 8: dbsentinel.ListBackups.created_at:type_name -> google.protobuf.Timestamp
	10, // 9: dbsentinel.DBSentinelService.StreamNodeStatus:input_type -> dbsentinel.StreamNodeStatusRequest
	4,  // 10: dbsentinel.DBSentinelService.TriggerBackup:input_type -> dbsentinel.BackupRequest
	6,  // 11: dbsentinel.DBSentinelService.TriggerRestoreVerification:input_type -> dbsentinel.VerificationRequest
	8,  // 12: dbsentinel.DBSentinelService.TriggerFailover:input_type -> dbsentinel.FailoverRequest
	11, // 13: dbsentinel.DBSentinelService.ListBackups:input_type -> dbsentinel.ListBackupsRequest
	3,  // 14: dbsentinel.DBSentinelService.StreamNodeStatus:output_type -> dbsentinel.NodeStatus
	5,  // 15: dbsentinel.DBSentinelService.TriggerBackup:output_type -> dbsentinel.BackupProgress
	7,  // 16: dbsentinel.DBSentinelService.TriggerRestoreVerification:output_type -> dbsentinel.VerificationResult
	9,  // 17: dbsentinel.DBSentinelService.TriggerFailover:output_type -> dbsentinel.FailoverResponse
	12, // 18: dbsentinel.DBSentinelService.ListBackups:output_type -> dbsentinel.ListBackupsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_dbsentinel_proto_init() }
func file_dbsentinel_proto_init() {
	if File_dbsentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dbsentinel_proto_rawDesc), len(file_dbsentinel_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbsentinel_proto_goTypes,
		DependencyIndexes: file_dbsentinel_proto_depIdxs,
		EnumInfos:         file_dbsentinel_proto_enumTypes,
		MessageInfos:      file_dbsentinel_proto_msgTypes,
	}.Build()
	File_dbsentinel_proto = out.File
	file_dbsentinel_proto_goTypes = nil
	file_dbsentinel_proto_depIdxs = nil
}
